package com.hub.media.features.portability.goodreads

import com.hub.media.features.portability.csv.CsvParseResult
import com.hub.media.features.portability.csv.CsvReader

/**
 * The `goodreads_library_export.csv` column names this importer looks for, by exact header text
 * (ROADMAP Task 8 Phase D). Verified against Goodreads' actual export (approximately): `Book Id,
 * Title, Author, Author l-f, Additional Authors, ISBN, ISBN13, My Rating, Average Rating,
 * Publisher, Binding, Number of Pages, Year Published, Original Publication Year, Date Read, Date
 * Added, Bookshelves, Bookshelves with positions, Exclusive Shelf, My Review, Spoiler, Private
 * Notes, Read Count, Owned Copies` -- every column not named here (`Book Id`, `Author`, `Author
 * l-f`, `Additional Authors`, `Average Rating`, `Publisher`, `Bookshelves with positions`, `My
 * Review`, `Spoiler`, `Private Notes`, `Owned Copies`) is simply never looked up, exactly as
 * tolerated for any other unknown/extra column (see [GoodreadsCsvTableReader]'s KDoc).
 */
public object GoodreadsColumns {
    public const val TITLE: String = "Title"
    public const val ISBN: String = "ISBN"
    public const val ISBN13: String = "ISBN13"
    public const val NUMBER_OF_PAGES: String = "Number of Pages"
    public const val BINDING: String = "Binding"
    public const val YEAR_PUBLISHED: String = "Year Published"
    public const val ORIGINAL_PUBLICATION_YEAR: String = "Original Publication Year"
    public const val EXCLUSIVE_SHELF: String = "Exclusive Shelf"
    public const val DATE_READ: String = "Date Read"
    public const val DATE_ADDED: String = "Date Added"

    /** No home in the schema yet -- see [GoodreadsCsvImporter.NOT_IMPORTED_COLUMNS_NOTICE]. */
    public const val MY_RATING: String = "My Rating"

    /** No home in the schema yet -- see [GoodreadsCsvImporter.NOT_IMPORTED_COLUMNS_NOTICE]. */
    public const val BOOKSHELVES: String = "Bookshelves"

    /** No home in the schema yet -- see [GoodreadsCsvImporter.NOT_IMPORTED_COLUMNS_NOTICE]. */
    public const val READ_COUNT: String = "Read Count"
}

/** Structurally-validated Goodreads table, or a description of why the file was rejected outright. */
public sealed class GoodreadsCsvTableResult {

    /**
     * @property columnIndex Every header cell's (trimmed) text mapped to its column position --
     *   [GoodreadsCsvImporter] looks columns up through this map, never by a hard-coded index.
     * @property rows Every data row (header stripped off), each already confirmed to have exactly
     *   [columnIndex]'s size fields.
     */
    public data class Success(
        public val columnIndex: Map<String, Int>,
        public val rows: List<List<String>>,
    ) : GoodreadsCsvTableResult()

    /** The file was rejected wholesale -- see [GoodreadsCsvTableReader]'s KDoc for what triggers this. */
    public data class Failure(public val message: String) : GoodreadsCsvTableResult()
}

/**
 * Structural, header-*tolerant* validation layer for a Goodreads `goodreads_library_export.csv`
 * (ROADMAP Task 8 Phase D) -- the Goodreads-specific counterpart to
 * [com.hub.media.features.portability.csv.CsvTableReader]. Deliberately a separate object rather
 * than a reuse of that one: [com.hub.media.features.portability.csv.CsvTableReader] demands the
 * header equal this app's own export shape *exactly*, which a Goodreads export -- a completely
 * different column set, in whatever order Goodreads happens to emit it, generated by a product
 * this app has no control over -- can never satisfy. What both readers *do* share is the
 * underlying tokenizer: every byte here still passes through [CsvReader], never a second
 * hand-rolled RFC 4180 parser (this phase's brief: "reuse the existing `CsvReader`; this is a
 * mapping layer, not a new parser").
 *
 * ### Column matching is by name, never by position
 * [columnIndex] on a [GoodreadsCsvTableResult.Success] maps every header cell's trimmed text to
 * its column index. [GoodreadsCsvImporter] looks up each field it wants by [GoodreadsColumns]
 * name through that map -- so a reordered export (Goodreads has changed its column order across
 * product versions), an export with extra/unknown columns this importer doesn't recognize, or one
 * missing an optional column entirely (that field just parses as "unknown" for every row) all
 * import cleanly. Only [GoodreadsColumns.TITLE] is required to exist at all -- its absence means
 * this doesn't look like a Goodreads library export, and the whole file is refused with a clear
 * message rather than silently importing zero usable books.
 *
 * ### Row-length mismatches are still whole-file, not per-row
 * A data row with a different field count than the header row is refused for the *whole* file --
 * the same "guessing which column shifted would risk silently misattributing a value" rationale
 * [com.hub.media.features.portability.csv.CsvTableReader]'s KDoc documents for this app's own
 * format applies identically here; a truncated/hand-edited Goodreads export is not something to
 * guess through.
 *
 * There is no `csv_schema_version` concept here at all -- that column only exists on this app's
 * own export format ([com.hub.media.features.portability.csv.CSV_SCHEMA_VERSION]'s KDoc); Goodreads
 * has no equivalent, and this importer has exactly one Goodreads export shape it understands (this
 * phase, today) with no historical versions to distinguish between.
 */
public object GoodreadsCsvTableReader {

    public fun read(text: String): GoodreadsCsvTableResult {
        val parsed = CsvReader.parse(text)
        val rows = when (parsed) {
            is CsvParseResult.Failure -> return GoodreadsCsvTableResult.Failure(parsed.message)
            is CsvParseResult.Success -> parsed.rows
        }

        if (rows.isEmpty()) {
            return GoodreadsCsvTableResult.Failure("The file is empty -- no header row was found.")
        }

        val header = rows.first()
        val columnIndex = header.withIndex().associate { (index, name) -> name.trim() to index }
        if (GoodreadsColumns.TITLE !in columnIndex) {
            return GoodreadsCsvTableResult.Failure(
                "Unrecognized file -- no '${GoodreadsColumns.TITLE}' column found. This doesn't look " +
                    "like a Goodreads library export (goodreads_library_export.csv).",
            )
        }

        val dataRows = rows.drop(1)
        dataRows.forEachIndexed { index, row ->
            if (row.size != header.size) {
                return GoodreadsCsvTableResult.Failure(
                    "Row ${index + 2} has ${row.size} column(s), expected ${header.size} -- the file " +
                        "may be truncated or corrupted.",
                )
            }
        }

        return GoodreadsCsvTableResult.Success(columnIndex, dataRows)
    }
}
