package com.hub.media.features.portability.domain

import androidx.room.useWriterConnection
import com.hub.media.core.database.AppDatabase
import com.hub.media.core.database.deleteFileIfExists
import com.hub.media.core.util.Resource
import com.hub.media.core.util.newId
import kotlin.time.Clock
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime

/**
 * Abstraction over "produce a whole-database backup snapshot" so
 * [com.hub.media.ui.BackupViewModel] can depend on a narrow contract instead of the concrete
 * [DefaultDatabaseBackupUseCase] -- mirrors [ExportUseCase]'s exact reason for existing (AGENTS.md
 * §5, no mocking library): `commonTest` can hand-roll a fake with no Room dependency.
 */
public interface DatabaseBackupUseCase {
    /** See [DefaultDatabaseBackupUseCase.execute]. */
    public suspend fun execute(): Resource<BackupResult>
}

/**
 * @property stagedFilePath Absolute path of a fresh, complete, self-contained SQLite file
 *   generated by this backup -- **not** the live database file itself, and not written to any
 *   user-visible location yet. Lives in the same directory as the live database (an app-private
 *   location no permission is needed to write to). The app layer is expected to copy the bytes at
 *   this path into the user-chosen SAF destination and then delete it, whether that copy succeeds
 *   or fails -- this use case does not clean it up itself, since deleting a plain local file needs
 *   no shared-layer involvement (AGENTS.md §6: only the app module touches
 *   `Uri`/`ContentResolver`, but a plain `java.io.File` in the app's own private storage is fine
 *   for the app module to manage directly).
 * @property suggestedFileName A timestamped default filename (`media_tracker_backup_<local
 *   date/time>.db`) for the SAF `CreateDocument` picker to prefill.
 */
public data class BackupResult(
    public val stagedFilePath: String,
    public val suggestedFileName: String,
)

/**
 * End-to-end ".sqlite backup" workflow (ROADMAP Task 8 Phase C): produces one complete, internally
 * consistent snapshot of the live database, ready for the app layer to hand to the user via SAF.
 *
 * ### WAL: why this doesn't need a manual checkpoint before copying anything
 * Room's `RoomDatabase.Builder` defaults to `JournalMode.WRITE_AHEAD_LOGGING` (confirmed against
 * the resolved `androidx.room:room-runtime` 2.8.4 bytecode: the builder's constructor sets this
 * journal mode unconditionally, and [com.hub.media.core.database.buildAppDatabase] never calls
 * `setJournalMode(TRUNCATE)` to override it) -- so this app's live database genuinely runs in WAL
 * mode. That matters because a WAL-mode database's most recently committed writes can live only in
 * the `-wal` sidecar file until SQLite next checkpoints them into the main `.db` file; naively
 * copying just the main file (`java.io.File(...).copyTo(...)`) can silently produce a backup
 * missing whatever hasn't been checkpointed yet.
 *
 * The fix here is **not** a manual `PRAGMA wal_checkpoint(TRUNCATE)` followed by a plain file copy
 * (an approach considered and rejected): that would mutate the *live* database's own WAL state,
 * and a `TRUNCATE` checkpoint can still leave the WAL non-empty if a concurrent reader (e.g. an
 * open `Flow` collector's snapshot) happens to be active at that exact moment, which would then
 * require copying the `-wal` file too and reasoning about matching it against the SAF picker's
 * one-document-per-pick constraint. Instead, this use case runs SQLite's own **`VACUUM INTO`**
 * command, which reads the database through the normal pager -- the same code path every ordinary
 * query already uses, which transparently merges the main file with anything still only in the WAL
 * -- and writes a fresh, compacted, single-file, WAL-free snapshot to [stagedFilePath]. This is the
 * mechanism SQLite's own documentation recommends specifically for taking a consistent backup of a
 * live, possibly-WAL-mode database: it never touches the live database's own files, never requires
 * a checkpoint, and never leaves a sidecar file to worry about. `DatabaseBackupUseCaseTest`
 * (`jvmTest`) proves this concretely: it inserts a row, confirms the live database's own `-wal`
 * file is genuinely non-trivial (i.e. the row has *not* been checkpointed into the main file) at
 * the moment of backup, then asserts the row is nonetheless present when the backup file is opened
 * fresh.
 *
 * ### `VACUUM INTO` and Room's raw-connection API
 * `VACUUM INTO ?` is executed via `AppDatabase.useWriterConnection { ... }` (Room KMP's public
 * suspend extension for running raw SQL against a pooled connection outside of any
 * DAO-generated code) plus `Transactor.usePrepared` to bind the destination path as a parameter
 * rather than string-concatenating it into the SQL text.
 *
 * @param database The live [AppDatabase] to snapshot.
 * @param databaseFilePath The live database's on-disk path (from
 *   [com.hub.media.core.database.DatabaseFactory.databaseFilePath]), used only to derive a sibling
 *   staging path in the same (already-writable, app-private) directory.
 */
public class DefaultDatabaseBackupUseCase(
    private val database: AppDatabase,
    private val databaseFilePath: String,
) : DatabaseBackupUseCase {

    override suspend fun execute(): Resource<BackupResult> {
        // A fresh, collision-free name every call (rather than a fixed name this use case would
        // otherwise need to delete-if-exists first) -- VACUUM INTO fails if its destination
        // already exists.
        val stagingPath = "$databaseFilePath.backup-${newId()}.tmp"
        return try {
            database.useWriterConnection { transactor ->
                transactor.usePrepared("VACUUM INTO ?") { statement ->
                    statement.bindText(1, stagingPath)
                    statement.step()
                }
            }
            Resource.Success(BackupResult(stagedFilePath = stagingPath, suggestedFileName = suggestedBackupFileName()))
        } catch (e: Exception) {
            deleteFileIfExists(stagingPath)
            Resource.Error("Backup failed: ${e.message ?: "Unknown error"}", e)
        }
    }
}

/**
 * A timestamped default filename for the backup SAF picker, e.g.
 * `media_tracker_backup_20260802_153045.db`. Takes an injectable [clock]/[timeZone] (mirroring
 * `StatsRepository`'s convention) so tests can assert on a deterministic name.
 */
public fun suggestedBackupFileName(
    clock: Clock = Clock.System,
    timeZone: TimeZone = TimeZone.currentSystemDefault(),
): String {
    val now = clock.now().toLocalDateTime(timeZone)
    fun pad(value: Int) = value.toString().padStart(2, '0')
    return "media_tracker_backup_${now.year}${pad(now.monthNumber)}${pad(now.dayOfMonth)}_" +
        "${pad(now.hour)}${pad(now.minute)}${pad(now.second)}.db"
}
