package com.hub.media.features.portability.domain

import androidx.room.useWriterConnection
import com.hub.media.core.database.AppDatabase
import com.hub.media.core.database.deleteFileIfExists
import com.hub.media.core.util.AppLogger
import com.hub.media.core.util.Logger
import com.hub.media.core.util.Resource
import com.hub.media.core.util.error
import com.hub.media.core.util.newId
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.withContext
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toLocalDateTime
import kotlin.coroutines.cancellation.CancellationException
import kotlin.time.Clock

/** Log tag for this file's adoption sites (ROADMAP Task 15 Phase C). */
private const val TAG = "DatabaseBackupUseCase"

/**
 * Abstraction over "produce a whole-database backup snapshot" so
 * [com.hub.media.ui.BackupViewModel] can depend on a narrow contract instead of the concrete
 * [DefaultDatabaseBackupUseCase] -- mirrors [ExportUseCase]'s exact reason for existing (AGENTS.md
 * §5, no mocking library): `commonTest` can hand-roll a fake with no Room dependency.
 */
public interface DatabaseBackupUseCase {
    /** See [DefaultDatabaseBackupUseCase.execute]. */
    public suspend fun execute(): Resource<BackupResult>
}

/**
 * @property stagedFilePath Absolute path of a fresh, complete, self-contained SQLite file
 *   generated by this backup -- **not** the live database file itself, and not written to any
 *   user-visible location yet. Lives in the same directory as the live database (an app-private
 *   location no permission is needed to write to). The app layer is expected to copy the bytes at
 *   this path into the user-chosen SAF destination and then delete it, whether that copy succeeds
 *   or fails -- this use case does not clean it up itself, since deleting a plain local file needs
 *   no shared-layer involvement (AGENTS.md §6: only the app module touches
 *   `Uri`/`ContentResolver`, but a plain `java.io.File` in the app's own private storage is fine
 *   for the app module to manage directly).
 * @property suggestedFileName A timestamped default filename (`media_tracker_backup_<local
 *   date/time>.db`) for the SAF `CreateDocument` picker to prefill.
 */
public data class BackupResult(
    public val stagedFilePath: String,
    public val suggestedFileName: String,
)

/**
 * End-to-end ".sqlite backup" workflow (ROADMAP Task 8 Phase C): produces one complete, internally
 * consistent snapshot of the live database, ready for the app layer to hand to the user via SAF.
 *
 * ### WAL: why this doesn't need a manual checkpoint before copying anything
 * Room's `RoomDatabase.Builder` defaults to `JournalMode.WRITE_AHEAD_LOGGING` (confirmed against
 * the resolved `androidx.room:room-runtime` 2.8.4 bytecode: the builder's constructor sets this
 * journal mode unconditionally, and [com.hub.media.core.database.buildAppDatabase] never calls
 * `setJournalMode(TRUNCATE)` to override it) -- so this app's live database genuinely runs in WAL
 * mode. That matters because a WAL-mode database's most recently committed writes can live only in
 * the `-wal` sidecar file until SQLite next checkpoints them into the main `.db` file; naively
 * copying just the main file (`java.io.File(...).copyTo(...)`) can silently produce a backup
 * missing whatever hasn't been checkpointed yet.
 *
 * The fix here is **not** a manual `PRAGMA wal_checkpoint(TRUNCATE)` followed by a plain file copy
 * (an approach considered and rejected): that would mutate the *live* database's own WAL state,
 * and a `TRUNCATE` checkpoint can still leave the WAL non-empty if a concurrent reader (e.g. an
 * open `Flow` collector's snapshot) happens to be active at that exact moment, which would then
 * require copying the `-wal` file too and reasoning about matching it against the SAF picker's
 * one-document-per-pick constraint. Instead, this use case runs SQLite's own **`VACUUM INTO`**
 * command, which reads the database through the normal pager -- the same code path every ordinary
 * query already uses, which transparently merges the main file with anything still only in the WAL
 * -- and writes a fresh, compacted, single-file, WAL-free snapshot to [stagedFilePath]. This is the
 * mechanism SQLite's own documentation recommends specifically for taking a consistent backup of a
 * live, possibly-WAL-mode database: it never touches the live database's own files, never requires
 * a checkpoint, and never leaves a sidecar file to worry about. `DatabaseBackupUseCaseTest`
 * (`jvmTest`) proves this concretely: it inserts a row, confirms the live database's own `-wal`
 * file is genuinely non-trivial (i.e. the row has *not* been checkpointed into the main file) at
 * the moment of backup, then asserts the row is nonetheless present when the backup file is opened
 * fresh.
 *
 * ### `VACUUM INTO` and Room's raw-connection API
 * `VACUUM INTO ?` is executed via `AppDatabase.useWriterConnection { ... }` (Room KMP's public
 * suspend extension for running raw SQL against a pooled connection outside of any
 * DAO-generated code) plus `Transactor.usePrepared` to bind the destination path as a parameter
 * rather than string-concatenating it into the SQL text.
 *
 * ### Why there is no "exclude log data" filter here (ROADMAP Task 15 Phase B)
 * There is no log-related code in this class, deliberately -- not an oversight to fill in later.
 * `VACUUM INTO` operates on [database] alone -- it reads and writes SQLite pages, nothing else on
 * disk -- so the resulting snapshot can only ever contain tables that genuinely exist in
 * [AppDatabase]'s Room schema. The persistent log store (Task 15 Phase B) is a flat file under
 * `<filesDir>/logs/`, deliberately **not** a Room table -- "that would bloat the database that
 * gets backed up and CSV-exported," per that task's own ROADMAP entry -- so it sits entirely
 * outside anything `VACUUM INTO` can touch, snapshot mode or not. This is a structural guarantee,
 * not a runtime check: a defensive "strip log rows" pass here would be dead code, since no table
 * this class writes to a backup could ever hold log content in the first place. **What must stay
 * true for this guarantee to hold:** the log store must never become a Room entity/table (any
 * `@Entity` Room adds is automatically snapshotted by `VACUUM INTO` -- there is no per-table
 * opt-out at this layer), and this class must never be changed to bundle arbitrary filesystem
 * paths alongside the database snapshot. The regression guard in `DatabaseBackupUseCaseTest`
 * queries the produced backup's own `sqlite_master` for any table name that looks log-related and
 * confirms a decoy log file sitting beside the live database never ends up inside the backup
 * bytes -- so a future change that *did* fold log data into either path would fail that test.
 *
 * @param database The live [AppDatabase] to snapshot.
 * @param databaseFilePath The live database's on-disk path (from
 *   [com.hub.media.core.database.DatabaseFactory.databaseFilePath]), used only to derive a sibling
 *   staging path in the same (already-writable, app-private) directory.
 */
public class DefaultDatabaseBackupUseCase(
    private val database: AppDatabase,
    private val databaseFilePath: String,
    private val logger: Logger = AppLogger,
) : DatabaseBackupUseCase {
    override suspend fun execute(): Resource<BackupResult> {
        // A fresh, collision-free name every call (rather than a fixed name this use case would
        // otherwise need to delete-if-exists first) -- VACUUM INTO fails if its destination
        // already exists.
        val stagingPath = "$databaseFilePath.backup-${newId()}.tmp"
        return try {
            database.useWriterConnection { transactor ->
                transactor.usePrepared("VACUUM INTO ?") { statement ->
                    statement.bindText(1, stagingPath)
                    statement.step()
                }
            }
            Resource.Success(BackupResult(stagedFilePath = stagingPath, suggestedFileName = suggestedBackupFileName()))
        } catch (e: CancellationException) {
            // Rethrown ahead of the Exception catch -- on JVM CancellationException is an Exception, so
            // swallowing it would break structured concurrency and log a cancelled screen as a failure.
            // Mirrors the Exception branch's cleanup below: VACUUM INTO's destination is created
            // before the statement finishes, so a cancellation landing mid-write can leave a
            // partial file at stagingPath just as surely as a thrown exception can. Wrapped in
            // NonCancellable because this coroutine's Job is already cancelled at this point --
            // without it, deleteFileIfExists's own withContext(Dispatchers.IO) hop would throw
            // CancellationException immediately on entry and never actually run the delete.
            withContext(NonCancellable) { deleteFileIfExists(stagingPath) }
            throw e
        } catch (e: Exception) {
            logger.error(TAG, e) { "Database backup failed" }
            deleteFileIfExists(stagingPath)
            Resource.Error("Backup failed: ${e.message ?: "Unknown error"}", e)
        }
    }
}

/**
 * A timestamped default filename for the backup SAF picker, e.g.
 * `media_tracker_backup_20260802_153045.db`. Takes an injectable [clock]/[timeZone] (mirroring
 * `StatsRepository`'s convention) so tests can assert on a deterministic name.
 */
public fun suggestedBackupFileName(
    clock: Clock = Clock.System,
    timeZone: TimeZone = TimeZone.currentSystemDefault(),
): String {
    val now = clock.now().toLocalDateTime(timeZone)

    fun pad(value: Int) = value.toString().padStart(2, '0')
    return "media_tracker_backup_${now.year}${pad(now.monthNumber)}${pad(now.dayOfMonth)}_" +
        "${pad(now.hour)}${pad(now.minute)}${pad(now.second)}.db"
}
